### ISSUE TITLE
After installation, not able to use itermocil

### ISSUE THREAD

**Issue by rogierlommers** [PythonicNinja/itermocil#1]
Hey! Thanks for your fork!
I do have an issue though: I installed itermocil using this command: `pip3 install git+https://github.com/PythonicNinja/itermocil`.
The output is like this:

```
Collecting git+https://github.com/PythonicNinja/itermocil
  Cloning https://github.com/PythonicNinja/itermocil to /private/var/folders/c9/w80j7zq926xgnhp4hhx0jlpm0000gp/T/pip-req-build-hqan7akx
  Running command git clone -q https://github.com/PythonicNinja/itermocil /private/var/folders/c9/w80j7zq926xgnhp4hhx0jlpm0000gp/T/pip-req-build-hqan7akx
Requirement already satisfied: PyYAML in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from itermocil==0.2.3) (6.0)
Using legacy setup.py install for itermocil, since package 'wheel' is not installed.
Installing collected packages: itermocil
    Running setup.py install for itermocil ... done
Successfully installed itermocil-0.2.3
WARNING: You are using pip version 20.1.1; however, version 22.0.4 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -m pip install --upgrade pip' command.
```

The output of `pip3 show itermocil` is like this:
```
Name: itermocil
Version: 0.2.3
Summary: Create pre-defined window/pane layouts and run commands in iTerm, updated to work with Python3
Home-page: https://github.com/PythonicNinja/itermocil
Author: Wojciech Nowak
Author-email: UNKNOWN
License: MIT
Location: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Requires: PyYAML
Required-by:
```

But I'm still not able to use it. Should I add it manually to my path or something similar?
(not a pyhon guy here ;) )

**Comment by PythonicNinja** [comment]
@rogierlommers did you try running in shell `$ itermocil`

it should work at this point.

**Comment by PythonicNinja** [comment]
@rogierlommers 
on osx it's being installed in:
```
| => which itermocil
itermocil is /usr/local/bin/itermocil
```

**Comment by rogierlommers** [comment]
> /usr/local/bin/itermocil

Although install succeeds, the binary isn't there:

```
[~]$ ll /usr/local/bin/itermocil
ls: /usr/local/bin/itermocil: No such file or directory
```

Thanks for your quick response, by the way!

**Comment by rogierlommers** [comment]
After (forcing) re-installation of python3 (using brew), it works fine now.

**Comment by PythonicNinja** [comment]
Cool 👍

**Comment by Leeiio** [comment]
When i use `itermocil test`, I am getting this
```
Traceback (most recent call last):
  File "/Users/Leeiio/.pyenv/versions/3.7.12/bin/itermocil", line 11, in <module>
    load_entry_point('itermocil==0.2.3', 'console_scripts', 'itermocil')()
  File "/Users/Leeiio/.pyenv/versions/3.7.12/lib/python3.7/site-packages/itermocil.py", line 752, in main
    instance = Itermocil(filepath, here=args.here, cwd=cwd)
  File "/Users/Leeiio/.pyenv/versions/3.7.12/lib/python3.7/site-packages/itermocil.py", line 79, in __init__
    self.process_file()
  File "/Users/Leeiio/.pyenv/versions/3.7.12/lib/python3.7/site-packages/itermocil.py", line 568, in process_file
    self.arrange_panes(len(window['panes']), layout)
  File "/Users/Leeiio/.pyenv/versions/3.7.12/lib/python3.7/site-packages/itermocil.py", line 262, in arrange_panes
    for p in range(0, second_columns):
TypeError: 'float' object cannot be interpreted as an integer
```

Anyone know how to solve this? I have zero knowledge in 🐍

**Comment by Leeiio** [comment]
open itermocil.py file, change the code in line 255 second_columns = num_panes / 2 to second_columns = num_panes // 2, done.
