### ISSUE TITLE
Float object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by zetlan** [PythonicNinja/itermocil#2]
I can submit this as a PR if you want, but for a 1-character change that seemed overkill.

https://github.com/PythonicNinja/itermocil/blob/cac94bdfd185af5910790addad0384211ab81cb7/itermocil.py#L255

The above line should read 
```
            second_columns = num_panes // 2
```

to avoid this traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/itermocil", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/itermocil.py", line 752, in main
    instance = Itermocil(filepath, here=args.here, cwd=cwd)
  File "/usr/local/lib/python3.9/site-packages/itermocil.py", line 79, in __init__
    self.process_file()
  File "/usr/local/lib/python3.9/site-packages/itermocil.py", line 568, in process_file
    self.arrange_panes(len(window['panes']), layout)
  File "/usr/local/lib/python3.9/site-packages/itermocil.py", line 262, in arrange_panes
    for p in range(0, second_columns):
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by PythonicNinja** [comment]
@zetlan fixed 👍
